import { Injectable } from '@nestjs/common';
import { AsyncLocalStorage } from 'async_hooks';

/**
 * Trace Service for request-level correlation.
 * Generates and stores trace_id per request using AsyncLocalStorage.
 * 
 * Per SPEC_PATCH.md: trace_id (uuid) — generated by server at ingress per request/turn.
 * MUST be stable for all writes performed for that turn (messages, decision trace, memory writes).
 */
@Injectable()
export class TraceService {
  private readonly asyncLocalStorage = new AsyncLocalStorage<string>();

  /**
   * Run a function within a trace context.
   * Generates a new trace_id if one doesn't exist.
   */
  run<T>(traceId: string | undefined, fn: () => T): T {
    const id = traceId || this.generateTraceId();
    return this.asyncLocalStorage.run(id, fn);
  }

  /**
   * Get the current trace_id from the async context.
   * Returns undefined if called outside of a trace context.
   */
  getTraceId(): string | undefined {
    return this.asyncLocalStorage.getStore();
  }

  /**
   * Generate a new UUID v4 trace_id.
   */
  private generateTraceId(): string {
    return crypto.randomUUID();
  }
}
